feat: Added CI and workflow logging

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -9,37 +9,62 @@ on:
 
 jobs:
     run-model-tests:
-        permissions:
-            contents: 'read'
-            id-token: 'write'
+      permissions:
+          contents: 'read'
+          id-token: 'write'
+      env:
+        LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
+        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
+        HF_TOKEN: ${{ secrets.HF_TOKEN }}
+        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
+        LANGSMITH_PROJECT: "linkedlens-test"
+        LANGSMITH_TRACING: "true"
+        LANGSMITH_ENDPOINT: "https://api.smith.langchain.com"
+        GOOGLE_PROJECT_ID: ${{ vars.GOOGLE_PROJECT_ID }}
+        PROMPT_VERSION_QUERY_ANALYZER: ${{ secrets.PROMPT_VERSION_QUERY_ANALYZER }}
+        PROMPT_ID_QUERY_ANALYZER: ${{ secrets.PROMPT_ID_QUERY_ANALYZER }}
+        PROMPT_VERSION_FINAL_RESPONSE: ${{ secrets.PROMPT_VERSION_FINAL_RESPONSE }}
+        PROMPT_ID_FINAL_RESPONSE: ${{ secrets.PROMPT_ID_FINAL_RESPONSE }}
+        GOOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOOGLE_APPLICATION_CREDENTIALS }}
+    
+      name: Model Unit Tests
+      runs-on: ubuntu-latest
+      defaults:
+        run:
+          working-directory: ./model-development/
+    
+      steps:
+      - name: 'Checkout'
+        uses: 'actions/checkout@v2'
       
-        name: Model Unit Tests
-        runs-on: ubuntu-latest
-    
-        steps:
-        - name: 'Checkout'
-          uses: 'actions/checkout@v2'
-        
-        - name: 'Set up Python'
-          uses: actions/setup-python@v2
-          with:
-            python-version: 3.12
-        
-        - name: Install dependencies
-          working-directory: model-development/src/
-          run: pip install -r requirements.txt
-        
-        - name: Run unittests
-          working-directory: model-development
-          run: python -m unittest test.test_unittest
-    
-        - name: Notify on model test success
-          if: success()
-          run: echo "Model Unit tests passed successfully"
-        
-        - name: Notify on model test failure
-          if: failure()
-          run: echo "Model Unit Tests failed."
+      - name: 'Set up Python'
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.12
+      
+      - name: Install dependencies
+        working-directory: ./src/
+        run: pip install -r requirements.txt
+      
+      - name: Run unittests
+        id: model-unit-test
+        working-directory: model-development
+        run: python -m unittest discover -s test || echo "Test failed"
+      
+      - name: Log on model test success
+        uses: ./.github/workflows/log-results.yml@main
+        with:
+          severity: ${{ steps.model-unit-test.outputs.result == 'Test failed' && 'ERROR' || 'INFO' }}
+          message: ${{ steps.model-unit-test.outputs.result == 'Test failed' && 'Model Unit tests failed' || 'Model Unit tests passed succesfully' }}
+          workflow_type: 'Unit Tests'
+          success: ${{ steps.model-unit-test.outputs.result == 'Test failed' && false || true }}
+      
+      - name: Calculate Commit Hash
+        run: echo "COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
+      
+      - name: Model evaluation
+        run: python pre_eval.py
+          
     
     run-data-pipeline-tests:
         permissions:
@@ -62,42 +87,33 @@ jobs:
           run: pip install -r requirements.txt
         
         - name: Run data generation unittests
+          id: data-gen-test
           working-directory: data-pipelines/data-generation/dags
-          run: python -m unittest test.test_unittest
+          run: python -m unittest test.test_unittest || echo "Test failed"
+
+        - name: Log on model test success
+          uses: ./.github/workflows/log-results.yml@main
+          with:
+            severity: ${{ steps.data-gen-test.outputs.result == 'Test failed' && 'ERROR' || 'INFO' }}
+            message: ${{ steps.data-gen-test.outputs.result == 'Test failed' && 'Data Generation Pipeline Unit tests failed' || 'Data Generation Pipeline Unit tests passed succesfully' }}
+            workflow_type: 'Unit Tests'
+            success: ${{ steps.data-gen-test.outputs.result == 'Test failed' && false || true }}
     
-        - name: Notify on success
-          if: success()
-          run: echo "Data Generation Unit tests passed successfully"
-        
-        - name: Notify on data generation test failure
-          if: failure()
-          run: echo "Data generation pipeline Unit Tests failed."
         
         - name: Run data ingestion unittests
+          id: data-ing-test
           working-directory: data-pipelines/data-ingestion/dags
-          run: python -m unittest test.test_unittest
-    
-        - name: Notify on success
-          if: success()
-          run: echo "Data Ingestion Unit tests passed successfully"
-
-        - name: Notify on data ingestion test failure
-          if: failure()
-          run: echo "Data ingestion pipeline Unit Tests failed."
-
-        # - name: Notify on failure
-        #   uses: hilarion5/send-mail@v1
-        #   with:
-        #     smtp-server: smtp.example.com
-        #     smtp-port: 465
-        #     smtp-secure: true
-        #     from-email: sender@example.com
-        #     to-email: recipient1@example.com,recipient2@example.com
-        #     username: yourusername
-        #     password: yourpassword
-        #     subject: Unit Test failed.
-        #     body: This is a test email sent from GitHub Actions.
-        #     html: |
-        #       <h1>This is a test email</h1>
-        #       <p>Test Paragraph</p>
+          run: pytest ./tests/
         
+        - name: Log data ingestion test result
+          uses: ./.github/workflows/log-results.yml@main
+          with:
+            severity: ${{ steps.data-ing-test.outputs.result == 'Test failed' && 'ERROR' || 'INFO' }}
+            message: ${{ steps.data-ing-test.outputs.result == 'Test failed' && 'Data Ingestion Pipeline Unit tests failed' || 'Data Ingestion Pipeline Unit tests passed succesfully' }}
+            workflow_type: 'Unit Tests'
+            success: ${{ steps.data-ing-test.outputs.result == 'Test failed' && false || true }}
+
+    deploy-model:
+      needs: run-model-tests
+      if: success()
+      uses: ./.github/workflows/deploy-to-gke.yaml@main
diff --git a/.github/workflows/deploy-to-gke.yml b/.github/workflows/deploy-to-gke.yml
--- a/.github/workflows/deploy-to-gke.yml
+++ b/.github/workflows/deploy-to-gke.yml
@@ -1,13 +1,14 @@
 name: Setup, Build, Deploy
 
 on:
-  push:
-    branches:
-      - main
-    paths:
-      - 'model-development/src/**'
-      - '.github/workflows/deploy-to-gke.yml'
-  workflow_dispatch:
+  workflow_call:
+  # push:
+  #   branches:
+  #     - main
+  #   paths:
+  #     - 'model-development/src/**'
+  #     - '.github/workflows/deploy-to-gke.yml'
+  # workflow_dispatch:
 
 jobs:
   setup-build-deploy-push:
@@ -73,13 +74,42 @@ jobs:
       - name: Check if ConfigMap exists
         id: check-configmap
         run: |
-          kubectl get configmap model-config -n default || echo "ConfigMap not found"
+          kubectl get configmap model-config -n app || echo "ConfigMap not found"
 
       - name: Apply ConfigMap if it doesn't exist
         if: steps.check-configmap.outputs.result == 'ConfigMap not found'
         run: |
           echo "ConfigMap not found. Applying..."
-          kubectl apply -f ../../kubernetes/config.yaml
+          sed -e "s/__PINECONE_ENVIRONMENT__/${{ secrets.PINECONE_ENVIRONMENT }}/g" \
+            -e "s/__GCP_PROJECT_ID__/${{ vars.GCP_PROJECT_ID }}/g" \
+            -e "s/__PROMPT_VERSION_QUERY_ANALYZER__/${{ vars.PROMPT_VERSION_QUERY_ANALYZER }}/g" \
+            -e "s/__PROMPT_ID_QUERY_ANALYZER__/${{ secrets.PROMPT_ID_QUERY_ANALYZER }}/g" \
+            -e "s/__PROMPT_VERSION_FINAL_RESPONSE__/${{ vars.PROMPT_VERSION_FINAL_RESPONSE }}/g" \
+            -e "s/__PROMPT_ID_FINAL_RESPONSE__/${{ secrets.PROMPT_ID_FINAL_RESPONSE }}/g" ./kubernetes/config.template.yaml > config.yaml
+          kubectl apply -f config.yaml -n app
+
+      - name: Check if Secrets exist
+        id: check-secrets
+        run: |
+            kubectl get secrets api-secrets -n app || echo "Secrets not found"
+  
+      - name: Apply Secrets if it doesn't exist
+        if: steps.check-secrets.outputs.result == 'Secrets not found'
+        run: |
+          echo "Secrets not found. Applying..."
+          set +x
+          echo "PINECONE_API_KEY=$(echo -n '${{ secrets.PINECONE_API_KEY }}' | base64)" >> secrets.env
+          echo "HF_TOKEN=$(echo -n '${{ secrets.HF_TOKEN }}' | base64)" >> secrets.env
+          echo "GEMINI_API_KEY=$(echo -n '${{ secrets.GEMINI_API_KEY }}' | base64)" >> secrets.env
+          echo "LANGSMITH_API_KEY=$(echo -n '${{ secrets.LANGSMITH_API_KEY }}' | base64)" >> secrets.env
+
+          source secrets.env
+          sed -e "s|__PINECONE_API_KEY__|$PINECONE_API_KEY|g" \
+            -e "s|__HF_TOKEN__|$HF_TOKEN|g" \
+            -e "s|__GEMINI_API_KEY__|$GEMINI_API_KEY|g" \
+            -e "s|__LANGSMITH_API_KEY__|$LANGSMITH_API_KEY|g"  ./kubernetes/secrets.template.yaml > secrets.yaml
+          set -x
+          kubectl apply -f secrets.yaml -n app
 
       - name: Apply image tag
         run: |-
@@ -94,9 +124,34 @@ jobs:
       - name: Restart deployment
         run: kubectl rollout restart deployment model-dev-deployment -n app
       
-      # - name: Status of deployment
-      #   run: | 
-      #     if ! kubectl rollout status deployment model-dev-deployment; then
-      #       exit 1
-      #     else
-      #       echo "Deployment successful"
+      - name: Cleanup temp files
+        run: rm -f secrets.env secrets.yaml config.yaml deployment.yaml
+        if: always()
+
+      - name: Check deployed Image Tag
+        id: check-deployed-tag
+        run: |-
+          echo "DEPLOY_SHA=kubectl describe deployments/model-dev-deployment -n app | grep Image | sed  -E "s/.*(.......)/\1/g" >> $GITHUB_ENV
+          if [ "$COMMIT_SHA" == "$DEPLOY_SHA" ]; then
+            echo "Deployment Succesful.."
+          else
+            echo "Deployment Unsuccessful.."
+          fi
+      
+      - name: Log Success
+        if: steps.check-deployed-tag.outputs.result == 'Deployment Succesful..'
+        uses: ./.github/workflows/log-results.yml@main
+        with:
+          severity: INFO
+          message: 'Deployment of Model version "$(COMMIT_SHA) successful"'
+          workflow_type: 'Deployment'
+          success: true
+      
+      - name: Log Success
+        if: steps.check-deployed-tag.outputs.result == 'Deployment Unsuccesful..'
+        uses: ./.github/workflows/log-results.yml@main
+        with:
+          severity: ERROR
+          message: 'Deployment of Model version "$(COMMIT_SHA) unsuccessful"'
+          workflow_type: 'Deployment'
+          success: false
