fix: check for config map

diff --git a/.github/workflows/deploy-to-gke.yml b/.github/workflows/deploy-to-gke.yml
--- a/.github/workflows/deploy-to-gke.yml
+++ b/.github/workflows/deploy-to-gke.yml
@@ -62,8 +62,17 @@ jobs:
       - name: Docker push
         run: docker push us-east1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/model-dev:$GITHUB_SHA
       
-      - name: 'Apply ConfigMap'
-        run: kubectl apply -f ../../kubernetes/config.yaml
+      - name: Check if ConfigMap exists
+        id: check-configmap
+        run: |
+          # Check if the ConfigMap exists. If it does, this will return a success status.
+          kubectl get configmap model-config -n default || echo "ConfigMap not found"
+
+      - name: Apply ConfigMap if it doesn't exist
+        if: steps.check-configmap.outputs.result == 'ConfigMap not found'
+        run: |
+          echo "ConfigMap not found. Applying..."
+          kubectl apply -f ../../kubernetes/config.yaml
       
       - name: Deploy
         run: |-
