Update update_code_vm.yml

diff --git a/.github/workflows/update_code_vm.yml b/.github/workflows/update_code_vm.yml
--- a/.github/workflows/update_code_vm.yml
+++ b/.github/workflows/update_code_vm.yml
@@ -19,12 +19,12 @@ jobs:
 
       - name: Test Network Connection
         run: |
-          nslookup 34.136.81.6 || echo "DNS Lookup Failed"
+          nslookup 35.238.94.54 || echo "DNS Lookup Failed"
           
       - name: execute remote ssh commands with password
         uses: appleboy/ssh-action@v1.2.1
         with:
-          host: 34.136.81.6
+          host: 35.238.94.54
           username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SERVER_KEY }}
           port: ${{ secrets.SSH_PORT }}
@@ -89,6 +89,6 @@ jobs:
               echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > ./credentials/linkedlens-firestore-srvc-acc.json
               
               # Set airflow UID
-              AIRFLOW_UID=$(id -u)
-              export AIRFLOW_UID=$AIRFLOW_UID
+              echo"$(id -u)"
+              export AIRFLOW_UID=$(id -u)
               echo "AIRFLOW_UID set to $AIRFLOW_UID"
