fix: update_code_vm.yml

diff --git a/.github/workflows/update_code_vm.yml b/.github/workflows/update_code_vm.yml
--- a/.github/workflows/update_code_vm.yml
+++ b/.github/workflows/update_code_vm.yml
@@ -19,12 +19,12 @@ jobs:
 
       - name: Test Network Connection
         run: |
-          nslookup 34.123.39.152 || echo "DNS Lookup Failed"
+          nslookup 34.10.226.163 || echo "DNS Lookup Failed"
           
       - name: execute remote ssh commands with password
         uses: appleboy/ssh-action@v1.2.1
         with:
-          host: 34.123.39.152
+          host: 34.10.226.163
           # username: ${{ secrets.SERVER_USERNAME }}
           username: apeksha.suhas.joshi
           key: ${{ secrets.SERVER_KEY }}
@@ -35,7 +35,6 @@ jobs:
               REPO_PATH="$(find /home -type d -name "LinkedLens" 2>/dev/null | head -n 1)"
               echo "Repo path is: $REPO_PATH"
               if [ ! -d "$REPO_PATH" ]; then
-                cd $HOME
                 echo "Repo not found, cloning..."
                 git clone https://github.com/jaynanduri/LinkedLens.git
                 echo "Repo cloned.."
