add load jobs DAG and Git to VM workflow

diff --git a/.github/workflows/update-dags.yml b/.github/workflows/update-dags.yml
--- a/.github/workflows/update-dags.yml
+++ b/.github/workflows/update-dags.yml
@@ -17,79 +17,91 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
-      
+
+      - name: Test Network Connection
+        run: |
+          nslookup ${{ secrets.SERVER_IP }} || echo "DNS Lookup Failed"
+          
       - name: execute remote ssh commands with password
-        uses: appleboy/ssh-action@master
+        uses: appleboy/ssh-action@v1.2.1
         with:
           host: ${{ secrets.SERVER_IP }}
           username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SERVER_KEY }}
+          port: 22
+          debug: true
           script: |
-            # Define repo path
-            REPO_PATH = "/home/${{ secrets.SERVER_USERNAME }}/mlops/LinedLens"
-
-            if [! -d "$REPO_PATH"]; then
-              echo "Repo not found, cloning..."
-              cd /home/${{ secrets.SERVER_USERNAME }}/mlops
-              git clone https://github.com/jaynanduri/LinkedLens.git
-            fi
-
-            cd "$REPO_PATH"
-
-            # #Navigate to repo
-            # cd "$(find /home -type d -name "LinkedLens" 2>/dev/null | head -n 1)"
-
-            git pull origin dev-data-generation
-
-            cd data-generation
-
-            #Verifying PWD
-            if [-d "./data-generation"]; then
-              echo "Correct directory"
-            else
-              echo "Repository not found. Exiting.."
-              exit 1
-            fi
-
-            # #Pull latest changes
-            # git pull
-            # cd ./data-generation
-
-            #Re-write env file
-
-            if [ ! -f .env ]; then
-              echo "Creating .env file..."
+              # Define repo path
+              REPO_PATH="$(find /home -type d -name "LinkedLens" 2>/dev/null | head -n 1)"
+              echo "Repo path is: $REPO_PATH"
+              if [ ! -d "$REPO_PATH" ]; then
+                echo "Repo not found, cloning..."
+                cd /home/${{ secrets.SERVER_USERNAME }}/mlops
+                git clone https://github.com/jaynanduri/LinkedLens.git
+              fi
+              echo "Did not clone repo"
+              cd "$REPO_PATH"
+  
+              # #Navigate to repo
+              # cd "$(find /home -type d -name "LinkedLens" 2>/dev/null | head -n 1)"
+              echo "running git pull.."
+              git pull origin dev-data-generation
+  
+              
+              #Verifying PWD
+              if [ -d "./data-generation" ]; then
+                echo "Correct directory"
+              else
+                echo "Repository not found. Exiting.."
+                exit 1
+              fi
+              
+              cd data-generation
+              echo "Current directory: $(pwd)"
+              
+              #Re-write env file
+              echo "Creating/Re-writing .env file"
               cat > .env <<EOF
-            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
-            DB_NAME=${{ secrets.DB_NAME }}
-            DB_CREDENTIALS_PATH=${{ secrets.DB_CREDENTIALS_PATH }}
-            AIRFLOW_UID=${{ secrets.AIRFLOW_UID }}
-            MAX_OPEN_AI_REQUEST_PER_MIN=${{ secrets.MAX_REQ_PER_MIN }}
-            MAX_OPEN_AI_REQUEST_PER_DAY=${{ secrets.MAX_REQ_PER_DAY }}
-            OPEN_ROUTER_BASE_URL=${{ secrets.OPEN_ROUTER_BASE_URL }}
-            SMTP_SERVER=${{ secrets.SMTP_SERVER }}
-            SMTP_STARTTLS=${{ secrets.SMTP_STARTTLS }}
-            SMTP_USER=${{ secrets.SMTP_USER }}
-            SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
-            SMTP_PORT=${{ secrets.SMTP_PORT }}
-            SMTP_EMAIL=${{ secrets.SMTP_EMAIL }}
-            SMTP_TIMEOUT=${{ secrets.SMTP_TIMEOUT }}
-            SMTP_RETRY_LIMIT=${{ secrets.SMTP_RETRY_LIMIT }}
-            SMTP_RECIPIENT_EMAILS=${{ secrets.SMTP_RECIPIENT_EMAILS }}
-            EOF
-            else
-              echo ".env file already exists. Skipping creation."
-            fi
-
-            mkdir -p dags/src/credentials
-
-            if [ ! -f dags/src/credentials/linkedlens-firestore-srvc-acc.json ]; then
-              echo "Creating linkedlens-firestore-srvc-acc.json.json..."
+              OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
+              DB_NAME=${{ secrets.DB_NAME }}
+              DB_CREDENTIALS_PATH=${{ secrets.DB_CREDENTIALS_PATH }}
+              AIRFLOW_UID=${{ secrets.AIRFLOW_UID }}
+              MAX_OPEN_AI_REQUEST_PER_MIN=${{ secrets.MAX_OPEN_AI_REQUEST_PER_MIN }}
+              MAX_OPEN_AI_REQUEST_PER_DAY=${{ secrets.MAX_OPEN_AI_REQUEST_PER_DAY }}
+              OPEN_ROUTER_BASE_URL=${{ secrets.OPEN_ROUTER_BASE_URL }}
+              SMTP_SERVER=${{ secrets.SMTP_SERVER }}
+              SMTP_STARTTLS=${{ secrets.SMTP_STARTTLS }}
+              SMTP_USER=${{ secrets.SMTP_USER }}
+              SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
+              SMTP_PORT=${{ secrets.SMTP_PORT }}
+              SMTP_EMAIL=${{ secrets.SMTP_EMAIL }}
+              SMTP_TIMEOUT=${{ secrets.SMTP_TIMEOUT }}
+              SMTP_RETRY_LIMIT=${{ secrets.SMTP_RETRY_LIMIT }}
+              SMTP_RECIPIENT_EMAILS=${{ secrets.SMTP_RECIPIENT_EMAILS }}
+              EOF
+              echo ".env file created"
+              
+              mkdir -p dags/src/credentials
+          
+              echo "Creating/Re-writing linkedlens-firestore-srvc-acc.json..."
               echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > dags/src/credentials/linkedlens-firestore-srvc-acc.json
-            else
-              echo "gcp_credentials.json already exists. Skipping creation."
-            fi
 
-            # #Restart Airflow
-            # docker-compose down &&
-            # docker-compose up -d
+              echo "Check if docker is running.."
+              if docker compose ps | grep "Up"; then
+                echo "Stopping running containers..."
+                docker compose down
+              else
+                echo "No running containers found."
+              fi
+
+              echo "Starting Docker Compose..."
+              docker compose up -d
+
+              echo "Waiting for services to be ready..."
+              while [[ $(docker compose ps | grep -c "healthy") -lt 1 ]]; do
+                echo "Waiting for containers to become healthy..."
+                sleep 5
+              done
+
+              echo "All services are up and healthy!"
+              echo "Airflow UI is available at: http://${{ secrets.SERVER_IP }}:8080"
