fix: update_code_vm.yml

diff --git a/.github/workflows/update_code_vm.yml b/.github/workflows/update_code_vm.yml
--- a/.github/workflows/update_code_vm.yml
+++ b/.github/workflows/update_code_vm.yml
@@ -19,14 +19,13 @@ jobs:
 
       - name: Test Network Connection
         run: |
-          nslookup 34.10.226.163 || echo "DNS Lookup Failed"
+          nslookup 34.136.81.6 || echo "DNS Lookup Failed"
           
       - name: execute remote ssh commands with password
         uses: appleboy/ssh-action@v1.2.1
         with:
-          host: 34.10.226.163
-          # username: ${{ secrets.SERVER_USERNAME }}
-          username: apeksha.suhas.joshi
+          host: 34.136.81.6
+          username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SERVER_KEY }}
           port: ${{ secrets.SSH_PORT }}
           debug: true
@@ -89,3 +88,6 @@ jobs:
               echo "Creating/Re-writing linkedlens-firestore-srvc-acc.json..."
               echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > ./credentials/linkedlens-firestore-srvc-acc.json
               
+              # Set airflow UID
+              export AIRFLOW_UID=$(id -u)
+              echo "AIRFLOW_UID set to $AIRFLOW_UID"
